# Adapted from https://github.com/huggingface/evaluate/blob/main/.github/workflows/ci.yml
name: CI (Run tests and check code quality)

#on:
#  pull_request:
#    branches:
#      - main
#  push:
#    branches:
#      - main

jobs:

  check_code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[quality]
      - name: Check quality
        run: |
          make check-quality

  test_genbench_impl:
    needs: check_code_quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install .[tests]
      - name: Test with pytest
        if: ${{ matrix.test == 'unit' }}
        run: |
          python -m pytest -n 2 -sv ./tests/ --ignore=./tests/test_task.py

  test_task:
    needs: test_genbench_impl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install .[tests]
      - name: Test with pytest
        run: |
          python -m pytest -n 2 -sv ./tests/ --ignore=./tests/test_task.py